name: Skematic
description: The Skript addon for FAWE.
version: 2.2
author: Efnilite
main: com.efnilite.skematic.Skematic
api-version: 1.13
website: https://forums.skunity.com/resources/skematic.671/
depend: [Skript]
softdepend: [FastAsyncWorldEdit]
